import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { type BundleItem } from "@/store/bundle";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function getBudgetColor(budgetPercentage: number) {
  if (budgetPercentage <= 75) return "#10B981";
  if (budgetPercentage <= 95) return "#F59E0B";
  return "#EF4444";
}

// AI generated function to export the selected items and their details to a PDF file
export async function exportBuildToPDF(
  selectedItems: BundleItem[],
  totalCost: number,
  maxBudget: number,
  fileName: string = "build-summary.pdf",
) {
  try {
    // Create a temporary container for rendering
    const container = document.createElement("div");
    container.style.position = "absolute";
    container.style.left = "-9999px";
    container.style.width = "800px";
    container.style.padding = "20px";
    container.style.backgroundColor = "#ffffff";
    container.style.fontFamily = "Arial, sans-serif";

    // Build HTML content
    const itemsHTML = selectedItems
      .map(
        (item) =>
          `<tr>
        <td style="padding: 8px; border-bottom: 1px solid #e0e0e0;">${item.category}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e0e0e0;">${item.name}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e0e0e0; text-align: right;">$${item.price}</td>
      </tr>`,
      )
      .join("");

    const remainingBudget = maxBudget - totalCost;
    const budgetStatus =
      remainingBudget >= 0
        ? `<span style="color: #10B981;">✓ Within Budget</span>`
        : `<span style="color: #EF4444;">✗ Over Budget by $${Math.abs(remainingBudget)}</span>`;

    container.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #4F46E5; margin: 0 0 10px 0; font-size: 28px;">Smart Bundle Builder</h1>
        <p style="color: #666; margin: 0; font-size: 14px;">Build Summary Report</p>
        <p style="color: #999; margin: 5px 0 0 0; font-size: 12px;">${new Date().toLocaleDateString()}</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <thead>
          <tr style="background-color: #f3f4f6;">
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #4F46E5; font-weight: bold;">Category</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #4F46E5; font-weight: bold;">Component</th>
            <th style="padding: 10px; text-align: right; border-bottom: 2px solid #4F46E5; font-weight: bold;">Price</th>
          </tr>
        </thead>
        <tbody>
          ${itemsHTML}
        </tbody>
      </table>

      <div style="background-color: #f9fafb; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
          <span style="font-weight: bold;">Total Cost:</span>
          <span style="font-size: 18px; color: #4F46E5; font-weight: bold;">$${totalCost}</span>
        </div>
        <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
          <span style="font-weight: bold;">Budget Limit:</span>
          <span>$${maxBudget}</span>
        </div>
        <div style="display: flex; justify-content: space-between; padding-top: 8px; border-top: 1px solid #e0e0e0;">
          <span style="font-weight: bold;">Remaining Budget:</span>
          <span style="font-weight: bold; color: ${remainingBudget >= 0 ? "#10B981" : "#EF4444"};">$${remainingBudget}</span>
        </div>
      </div>

      <div style="text-align: center; padding: 15px; background-color: #f0f4ff; border-radius: 8px;">
        ${budgetStatus}
      </div>

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; color: #999; font-size: 12px;">
        <p>Generated by Smart Bundle Builder</p>
      </div>
    `;

    document.body.appendChild(container);

    // Convert HTML to canvas
    const canvas = await html2canvas(container, {
      backgroundColor: "#ffffff",
      scale: 2,
    });

    // Create PDF
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const imgData = canvas.toDataURL("image/png");
    const imgWidth = 210; // A4 width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);
    pdf.save(fileName);

    // Cleanup
    document.body.removeChild(container);
  } catch (error) {
    console.error("Error exporting PDF:", error);
    throw error;
  }
}
